### ISSUE TITLE
ZIndexBehavior Global Support

### ISSUE THREAD

**Issue by TheNickmaster21** [boatbomber/GraphModule#1]
Currently this module only works correctly when ZIndexBehavior is set to "Sibling" on the top level ScreenGui. When set to "Global", the labels are hidden behind the graph itself. 

ZIndexes should be changed for the label text so the labels are not behind the graph when ZIndexBehavior is set to Global.

Thanks!

**Comment by boatbomber** [comment]
Good catch. I need to redo all the ZIndexes to support global, and ensure that they are relative to the Frame so they don't accidentally get entirely hidden by the Frame itself.

**Comment by boatbomber** [comment]
Fixed in this commit:
https://github.com/boatbomber/GraphModule/commit/2971e258b0ac906b4ca12619a5538aa9273a98ad
